title: Noah Frank # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Junior Data Scientist
  <br><br>
  <p align="justify">Master of Computer Engineering graduate with 2+ years of co-op experience and project work with Python, R, and SQL. Shows understanding of current machine learning research through the implementation of a computer vision system to assist physicians with breast cancer screening. Proven track record of software development working on Nokia’s network management software, used by clients globally. Exhibits curiosity and creativity while working on personal projects to expand data science skills. Looking to leverage my data science abilities to help make an impact.</p>
  <br><br>
  <p>Master of Computer Engineering graduate with 2+ years of co-op experience and project work with Python, R, and SQL. Shows understanding of current machine learning research through the implementation of a computer vision system to assist physicians with breast cancer screening. Proven track record of software development working on Nokia’s network management software, used by clients globally. Exhibits curiosity and creativity while working on personal projects to expand data science skills. Looking to leverage my data science abilities to help make an impact.</p>
  <br><br>
  <a href="https://www.linkedin.com/in/noahefrank/">View My LinkedIn Profile</a>
  <br><br>
  <a href="mailto:nefrank@outlook.com">Contact Me</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
