title: Noah Frank # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Junior Data Scientist
  <br>
  <p>Master of Computer Engineering graduate with 2+ years of industry experience and project work with Python, R, and SQL. Passionate about using data to help others. </p>
  <br>
  <a href="/pdf/NFCV_2P.pdf">View My Resume/CV</a>
  <a href="https://www.linkedin.com/in/noahefrank/">View My LinkedIn Profile</a>
  <a href="https://www.github.com/nefrank">View My GitHub</a>
  <a href="mailto:nefrank@outlook.com">Contact Me</a>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
